#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

#scripts/pre-push.sh

time {
#  npm run lint:scss &
#  npm run lint:ts &
#  npm run test:unit &
#  npm run build:prod &
  npm run storybook:build
  npm run test:ui:ci
}